### ISSUE TITLE
Plugin 3.4.4 on WordPress 4.9.6 with erro in settings page and activation plugin

### ISSUE THREAD

**Issue by everaldomatias** [mitchelldmiller/quick-mail-wp-plugin#11] opened 2018-06-07 19:53 UTC
First, in activation plugin the error is:
Fatal error: Cannot redeclare class QuickMail in /public_html/xxxxxxxxx.com.br/wp-content/plugins/quick-mail/quick-mail.php on line 42

Second, on click settings page the error is:
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 64 bytes) in /public_html/xxxxxxxxx.com.br/wp-includes/wp-db.php on line 2516

**Comment by mitchelldmiller** [comment] 2018-06-07 22:00
Hello Everaldo:
Thank you for testing Quick Mail.

> Cannot redeclare class QuickMail

You have an active plugin with a `QuickMail` class.
Can you send me a list of active plugins, so I can investigate?

It's easy to get a list to copy / paste with [WP-CLI](https://github.com/wp-cli/wp-cli) using: `wp plugin list --status=active`

I can add a namespace, if another plugin uses the same class name.

> Second, on click settings page the error is: Fatal error: Allowed memory size of 268435456 bytes exhausted 

You need more free memory. You can increase memory in [wp-config.php](https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP) using:

`define('WP_MEMORY_LIMIT', '384M');`
`define('WP_MAX_MEMORY_LIMIT', '512M');`

Best wishes,
Mitchell

**Comment by mitchelldmiller** [comment] 2018-08-20 01:15
Hello Everaldo:
Closing: I cannot reproduce error, and you have not replied.

Best wishes,
Mitchell

**Closed by mitchelldmiller** 2018-08-20 01:15 UTC
